import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { ToastContainer } from 'react-toastify';
import { ProviderParallax } from '@/app/providerParallax';
import { ThemeProvider } from '@/app/providers'
import Footer from '@/app/ui/footer';
import { ShoppingCartProvider } from '@/app/context/cart-context'; 
import '@/app/globals.css';

export const metadata: Metadata = {
  title: {
    default: "Nextjs 14 Skateboard",
    template: "%s | Shop"
  },
  description: 'Generated by NextJS14',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const DynamicHeader = dynamic(() => import('@/app/ui/header'), {
    loading: () => <p>Loading...</p>,
  });
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='bg-background'>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ProviderParallax>
            <ShoppingCartProvider>
              <DynamicHeader />
              <ToastContainer />
                {children}
              <Footer />
            </ShoppingCartProvider>
          </ProviderParallax>
        </ThemeProvider>
      </body>
    </html>
  )
}